# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_server: <%= ENV["SMTP_SERVER"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  google_map_key: <%= ENV["GOOGLE_MAP_KEY"] %>
  google_map_key: <%= ENV["DEFAULT_ADMIN_EMAIL"] %>
  default_admin_email: <%= ENV["DEFAULT_ADMIN_EMAIL"] %>
  default_admin_password: <%= ENV["DEFAULT_ADMIN_PASSWORD"] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default